config/routes.rb
Rates::Application.routes.draw do

  resources :accounts

  devise_for :account_holders
  devise_for :admins

  get "changelog_report" => "reports#changelog"

  get "accounts/:id/change_account_holder" => "accounts#change_account_holder", as: :change_account_holder
  get "accounts/:id/update_account_holder" => "accounts#update_account_holder", as: :update_account_holder

  root "pages#home"

  

end

app/models/account.rb
class Account < ActiveRecord::Base
    belongs_to :account_holder
    belongs_to :area
    belongs_to :catagory
    has_many :change_logs
end

app/models/account_holder.rb
class AccountHolder < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  has_many :accounts
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
  has_many :change_logs
end

app/models/area.rb
class Area < ActiveRecord::Base
    has_many :accounts
end

app/models/catagory.rb
class Catagory < ActiveRecord::Base
    has_many :accounts
end

app/models/change_log.rb
class ChangeLog < ActiveRecord::Base
    belongs_to :admin
    belongs_to :account

    after_initialize :set_default

    def set_default
        self.date ||= Date.today
        self.time ||= Time.now
    end

    def self.account_created(account_id, admin_id)
        self.create(:account_id => account_id, :admin_id => admin_id,
                    :comment => "Account created")
    end

    def self.change_account_holder(account, admin, params)
        log = self.new(:account => account, :admin => admin, :column => "account holder id")

        log.from = account.account_holder_id
        log.to = params[:account_holder_id]
        log.supporting_document = params[:supporting_document]
        log.comment = params[:comment]

        if account.update(:account_holder_id => params[:account_holder_id])
            log.save
            return true
        end
        return false
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_admin!, only: [:index]
    before_action :can_create, only: [:new, :create, :destroy]
    before_action :can_update, only: [:edit, :update]

  before_action :set_account, only: [:change_account_holder, :update_account_holder, :show, :edit, :update, :destroy]

  def change_account_holder
  end

  def update_account_holder
      if ChangeLog.change_account_holder(@account, current_admin, account_holder_params)
          redirect_to @account
      else
          redirect_to @account
      end
  end

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
          ChangeLog.account_created(@account.id, current_admin.id)
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:accno, :plotno, :address, :area_id, :catagory_id, :property_value, :hecter, :description, :land_value, :improved, :TRV)
    end

    def account_holder_params
        params.permit(:account_holder_id, :comments, :supporting_documents)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include AdminHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def changelog
      @changelogs = ChangeLog.all
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
    def can_manage
        if admin_signed_in?
            deny_access("You do not have permission to view this page") unless current_admin.can_manage
        else
            must_sign_in
        end
    end

    def can_update
        if admin_signed_in?
            deny_access("You do not have permission to view this page") unless current_admin.can_update
        else
            must_sign_in
        end
    end

    def can_create
        if admin_signed_in?
            deny_access("You do not have permission to view this page") unless current_admin.can_create
        else
            must_sign_in
        end
    end

    def can_report
        if admin_signed_in?
            deny_access("You do not have permission to view this page") unless current_admin.can_re
        else
            must_sign_in
        end
    end

    def can_sell
    end


    def must_sign_in
        redirect_to new_admin_session_path, :notice => "You must be signed in to view this page"
    end

    def deny_access(notice)
        redirect_to root_path, :notice => notice
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :accno %><br>
    <%= f.text_field :accno %>
  </div>
  <div class="field">
    <%= f.label :plotno %><br>
    <%= f.text_field :plotno %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

    <div class="field">
        <%= f.label :area_id %><br />
        <%= f.select :area_id, options_from_collection_for_select(Area.all, "id","name") %>
    </div>

    <div class="field">
        <%= f.label :catagory_id %><br />
        <%= f.select :catagory_id, options_from_collection_for_select(Catagory.all, "id","name") %>
    </div>

  <div class="field">
    <%= f.label :property_value %><br>
    <%= f.text_field :property_value %>
  </div>
  <div class="field">
    <%= f.label :hecter %><br>
    <%= f.text_field :hecter %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :land_value %><br>
    <%= f.text_field :land_value %>
  </div>
  <div class="field">
    <%= f.label :improved %><br>
    <%= f.text_field :improved %>
  </div>
  <div class="field">
    <%= f.label :TRV %><br>
    <%= f.text_field :TRV %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/change_account_holder.html.erb
<%= form_tag update_account_holder_path(@account.id), :method => "get" do %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
        <%= label_tag :account_holder_id %><br />
        <%= select_tag :account_holder_id, options_from_collection_for_select(AccountHolder.all, "id","name") %>
    </div>

    <%= text_field_tag :supporting_documents %><br>
    <%= text_field_tag :comments %>

    <%= submit_tag "Update" %>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Accno</th>
      <th>Plotno</th>
      <th>Address</th>
      <th>Area</th>
      <th>Catagory</th>
      <th>Property value</th>
      <th>Hecter</th>
      <th>Description</th>
      <th>Land value</th>
      <th>Improved</th>
      <th>Trv</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.accno %></td>
        <td><%= account.plotno %></td>
        <td><%= account.address %></td>
        <td><%= account.area_id %></td>
        <td><%= account.catagory_id %></td>
        <td><%= account.property_value %></td>
        <td><%= account.hecter %></td>
        <td><%= account.description %></td>
        <td><%= account.land_value %></td>
        <td><%= account.improved %></td>
        <td><%= account.TRV %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Change Account Holder', change_account_holder_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accno:</strong>
  <%= @account.accno %>
</p>

<p>
  <strong>Plotno:</strong>
  <%= @account.plotno %>
</p>

<p>
  <strong>Address:</strong>
  <%= @account.address %>
</p>

<p>
  <strong>Area:</strong>
  <%= @account.area_id %>
</p>

<p>
  <strong>Catagory:</strong>
  <%= @account.catagory_id %>
</p>

<p>
  <strong>Property value:</strong>
  <%= @account.property_value %>
</p>

<p>
  <strong>Hecter:</strong>
  <%= @account.hecter %>
</p>

<p>
  <strong>Description:</strong>
  <%= @account.description %>
</p>

<p>
  <strong>Land value:</strong>
  <%= @account.land_value %>
</p>

<p>
  <strong>Improved:</strong>
  <%= @account.improved %>
</p>

<p>
  <strong>Trv:</strong>
  <%= @account.TRV %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rates</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <% if alert %> <p class="notice"><%= notice %></p> <% end %>
    <% if alert %> <p class="alert"><%= alert %></p> <% end %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Admin sign in", new_admin_session_path %> | <%= link_to "Admin sign out", destroy_admin_session_path, :method => "delete" %>
<br>
<%= link_to "Account holder sign in", new_account_holder_session_path %> | <%= link_to "Account holder sign out", destroy_account_holder_session_path, :method => "delete" %>

app/views/reports/changelog.html.erb
<% @changelogs.each do |changelog| %>
    <div>
        Date: <%= changelog.date %><br>
        Time: <%= changelog.time %><br>
        Account: <%= changelog.account.accno %><br>
        Column: <%= changelog.column %><br>
        From: <%= changelog.from %><br>
        To: <%= changelog.to %><br>
        Supporting document: <%= changelog.supporting_document %><br>
        Comment: <%= changelog.comment %><br>
        <br>
        Done By: <%= changelog.admin.name %><br>
        <br>
        <br>
    </div>
<% end %>